# Generated by Django 4.2.24 on 2025-09-06 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main headline for this slide', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle/description', max_length=300)),
                ('background_image', models.ImageField(help_text='Full-width background image (recommended: 1920x900px)', upload_to='hero_slides/')),
                ('call_to_action_text', models.CharField(blank=True, help_text="Button text (e.g., 'Learn More')", max_length=100)),
                ('call_to_action_url', models.CharField(blank=True, help_text='Button link URL', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('published', models.BooleanField(default=True, help_text='Show this slide on the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hero Carousel Slide',
                'verbose_name_plural': 'Hero Carousel Slides',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
