# Generated by Django 4.2.24 on 2025-09-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_heroslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='church_logo',
            field=models.ImageField(blank=True, help_text='Church logo (recommended: square format, 400x400px)', null=True, upload_to='homepage/'),
        ),
    ]
